In [ ]:
import pandas as pd
import numpy as np
import h5py
from scipy.stats import ortho_group
from scipy.sparse import csc_matrix, diags
from scipy.sparse.linalg import svds
mat = h5py.File('IPCADATA_FNW36_RNKDMN_CON.mat')
mat_t = np.transpose(mat['X'])
np.save('test.npy', mat_t)
X= np.load('test.npy')
GammaBeta_initial,s,v=svds(X.T@X, k=5)
GammaBeta_initial.shape


(599, 5)

simulate v, epsilon, f, to calculate r based on gammabeta

In [ ]:
v=[]
for i in range(1,38):
    v.append(np.random.normal(0,1,5))
v=np.array(v)

Z=[]
for i in range(1,38):
    Z.append(np.random.normal(0,1,599))
Z=np.array(Z)
Z.shape

f=np.random.normal(0,1,5)
f.reshape(1,-1)

epsilon=np.random.normal(0,1,37)
epsilon=epsilon.reshape(1,-1)
epsilon=epsilon.transpose()

(37, 1)

In [ ]:
beta=Z@GammaBeta_initial+v
r=beta@f
r=r.reshape(1,-1).transpose()
r=r+epsilon
r

array([[-1.21546813e+00],
       [ 1.55320906e+00],
       [-3.76840256e+00],
       [-1.62764822e+00],
       [ 3.20367833e+00],
       [ 1.41527439e+00],
       [-5.04394147e+00],
       [-1.26616374e+00],
       [ 3.79795759e+00],
       [ 1.83992966e+00],
       [ 6.27158305e+00],
       [-2.77964471e+00],
       [ 1.89701475e+00],
       [ 1.61719898e+00],
       [ 2.44702971e+00],
       [-2.77777875e+00],
       [-3.81413422e-01],
       [ 1.48972312e-01],
       [-9.27996616e-01],
       [ 3.92401804e+00],
       [ 2.58768577e+00],
       [ 7.10564938e+00],
       [ 6.69729538e+00],
       [ 2.16898422e+00],
       [-4.63521536e+00],
       [-4.28430455e-01],
       [ 9.67399673e+00],
       [-3.39249430e-02],
       [-3.66854572e+00],
       [-2.99597460e+00],
       [ 2.31046304e+00],
       [-9.46393291e-01],
       [ 4.99320315e+00],
       [ 4.96620374e+00],
       [-3.90049139e+00],
       [ 4.12317078e+01],
       [-1.32448050e+00]])

simulate v, epsilon, f, to calculate gammabeta based on r

In [ ]:
v=[]
for i in range(1,38):
    v.append(np.random.normal(0,1,5))
v=np.array(v)

Z=[]
X=[]
for i in range(1,38):
    Z.append(np.random.normal(0,1,599))
    z=Z[i-1].reshape(1,-1)
    X.append(z.transpose()@r[i-1]/37)
Z=np.array(Z)
X=np.array(X)


f=np.random.normal(0,1,5)
f.reshape(1,-1)

epsilon=np.random.normal(0,1,37)
epsilon=epsilon.reshape(1,-1)
epsilon=epsilon.transpose()


In [ ]:
GammaBeta_initial,s,u=svds(X.T@X, k=5)
beta=Z@GammaBeta_initial+v
r1=beta@f
r1=r1.reshape(1,-1).transpose()
r1=r1+epsilon
r1

array([[-5.55376791e+00],
       [-3.28109988e+00],
       [-4.44336352e+00],
       [-2.83689797e+00],
       [ 3.43334083e+00],
       [ 7.73041001e-01],
       [-1.05104907e+01],
       [ 2.34668397e-01],
       [ 3.51617169e+00],
       [ 3.34497567e-01],
       [ 6.12674476e+00],
       [-5.24571876e+00],
       [-4.91644793e+00],
       [-3.47029685e-02],
       [-1.19610533e+00],
       [-3.15446297e+00],
       [-4.16229818e+00],
       [-1.00302679e+00],
       [ 7.67514460e-01],
       [ 1.04153794e+00],
       [ 1.80287755e-01],
       [-8.10428524e+00],
       [ 2.15433210e+00],
       [ 1.79318875e+00],
       [-2.69810869e+00],
       [-1.75471327e+00],
       [-1.65491509e+01],
       [-1.39597992e+00],
       [-3.72810857e+00],
       [-6.90141972e-02],
       [ 7.31119500e-02],
       [-6.36337133e-01],
       [ 8.41659537e-01],
       [-5.82289857e+00],
       [-4.17343974e+00],
       [ 3.98880748e+01],
       [-9.89471992e-01]])

In [ ]:
rs=r-r1
rd=r-np.mean(r)

In [ ]:
sum_squared_regression = sum(num ** 2 for num in rs)
total_sum_of_squares = sum(num ** 2 for num in rd)

In [ ]:
total_sum_of_squares
1-sum_squared_regression/total_sum_of_squares
#r_squared

array([0.37349831])